### ISSUE TITLE
How to run tests in correct way

### ISSUE THREAD

**Issue by sergii-d** [accesto/PayumPayU#13]
Hi
Maybe it is stupid but I cant run your tests.

While running: _phpunit --configuration phpunit.xml.dist_
I get: No tests are executed

While running some test directly:
_phpunit --bootstrap Tests/bootstrap.php Tests/PayUGatewayFactoryTest.php_

I am getting:
PHP Fatal error:  Uncaught PHPUnit\Runner\Exception: Class 'Tests/PayUGatewayFactoryTest' could not be found

So, how your tests should be run?

**Comment by mkurzeja** [comment]
Hi,

after cloning the repository, cd into the directory and just run:
```
composer install
bin/phpunit
```

The first one installs vendors and dumps the autoload. In your case, the autoload might be missing or it's just a phpunit version mismatch because it seems you have used your own.

Let me know if that worked :)

**Comment by sergii-d** [comment]
Ok, it works
Thanks
